### ISSUE TITLE
RC: Open edX studio doesn't load due to a theme error

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#587]
### Steps to Reproduce

- Go to https://studio-qa.mitxonline.mit.edu/

### Expected Behavior

- Open edX studio should load

### Actual Behavior

- Internal Server Error

### Stacktrace

@blarghmatey diagnosed this as a theme error with the latest release of edX:
```
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/lookup.py", line 241, in get_template
    return self._check(uri, self._collection[uri])
KeyError: 'mitxonline/cms/templates/widgets/footer.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/exception.py", line 153, in handle_uncaught_exception
    return callback(request)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/util/views.py", line 95, in wrapper
    return func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/error.py", line 26, in inner
    return func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/error.py", line 50, in render_500
    return HttpResponseServerError(render_to_string('500.html', {}, request=request))
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 178, in render_to_string
    return template.render(dictionary, request)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/template.py", line 82, in render
    return self.mako_template.render_unicode(**context_dictionary)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/template.py", line 444, in render_unicode
    return runtime._render(
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/runtime.py", line 874, in _render
    _render_context(
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/runtime.py", line 916, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/runtime.py", line 943, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/mako_cms/f13f950116d269293ac438cd8e2ded58/base.html.py", line 279, in render_body
    runtime._include_file(context, 'widgets/footer.html', _template_uri)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/runtime.py", line 780, in _include_file
    template = _lookup_template(context, uri, calling_uri)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/runtime.py", line 837, in _lookup_template
    return lookup.get_template(uri)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/paths.py", line 102, in get_template
    template = super().get_template(get_template_path_with_theme(uri))
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/lookup.py", line 252, in get_template
    return self._load(srcfile, uri)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/lookup.py", line 313, in _load
    self._collection[uri] = template = Template(
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/template.py", line 317, in __init__
    module = self._compile_from_file(path, filename)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/template.py", line 381, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/compat.py", line 53, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/mako_cms/f13f950116d269293ac438cd8e2ded58/mitxonline/cms/templates/widgets/footer.html.py", line 22, in <module>
    from cms.djangoapps.contentstore.config.waffle import waffle, ENABLE_ACCESSIBILITY_POLICY_PAGE
ImportError: cannot import name 'waffle' from 'cms.djangoapps.contentstore.config.waffle' (/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/config/waffle.py)
```

The theme repo: https://github.com/mitodl/mitxonline-theme

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/21342568/170117966-3bcc5595-e6e2-4576-8b47-5c397dcaeb04.png)

**Comment by pdpinch** [comment]
I'm pretty sure this is working now.

**Comment by arslanashraf7** [comment]
> I'm pretty sure this is working now.

Correct! Thanks for closing this issue.
